### ISSUE TITLE
Perspective pull down menu or created entity are not showing on home page.

### ISSUE THREAD

**Issue by alooteche** [Coevery/Coevery#1]
I created a lead entity and a sales perspective, but neither are showing on the home page. Left sidebar of the home page is completely blank with "Welcome" message on content area.

**Comment by CloudyAvalon** [comment]
The project is under some magnificent change, so we are sorry that currently we may not reply your question actively. 
Your problem may be no navigation items for your entity, you can go to the "Manage Perspective" view and add navigation for it. If that doesn't help, you'd better wait for about one week and fetch our new develop version.
BTW, thanks for your concerning.
