### ISSUE TITLE
Number类型的字段长度和小数位数验证错误

### ISSUE THREAD

**Issue by ZhouGinn** [Coevery/Coevery#29]
Number类型的字段在后台建立的时候保留两位小数，length设置为18。在前台录入数据的时候输入的number满足以上条件，但还是会报错。
例如，输入1111.3就会报如下错误。
![image](https://f.cloud.github.com/assets/5396365/1570317/3ef6f556-50e9-11e3-8760-d752d5d2429a.png)

**Comment by ZhouGinn** [comment]
该bug比较紧急。

**Comment by icese7en** [comment]
该Bug已被修复。
