### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Gsonovb** [Coevery/Coevery#3]
我点击了ClickToBuild， 但结果有错误。

“E:\samples\Coevery\Coevery-develop\Orchard.proj”(Build 目标) (1) ->
Test 目标) ->
 NUNIT : 1) Test error : Orchard.Projections.Tests.Services.FieldIndexServiceT
sts.BooleanValuesShouldBePersisted [E:\samples\Coevery\Coevery-develop\Orchard

 NUNIT : 11) Test error : Orchard.Projections.Tests.Services.FieldIndexStorage
ests.StringsShouldBeTruncated [E:\samples\Coevery\Coevery-develop\Orchard.proj

 NUNIT : 12) Test error : Orchard.Projections.Tests.Services.FieldIndexStorage
ests.ValueThatIsSetIsIndexed [E:\samples\Coevery\Coevery-develop\Orchard.proj]

   35 个警告
   12 个错误

该怎么办，另外这个是基于 Orchard 那个版本制作的？最新的1.7.1 吗？谢谢

**Comment by CloudyAvalon** [comment]
执行build的对象应该是Orchard.Web.csproj；
当前Coevery基于Orchard 1.7.1，感谢你的关注。

**Comment by Gsonovb** [comment]
哦，我再试试，个人比较习惯使用WebMatrix 跑测试 。

另外，请问这个  和  https://coevery.codeplex.com/  有什么关系吗？

PS。能有中文的太好了。。

**Comment by CloudyAvalon** [comment]
该版本目前还不支持中文。。。
https://coevery.codeplex.com/ 上的原本是Windows版的Coevery，也是我们项目组制作的，现在换成Web版的了，也就是GitHub上的这个版本

**Comment by Gsonovb** [comment]
哦， 怪不得我没成功

另外，你们和 http://www.novasoftware.cn/ 公司有关吗？
公司这么随意的制作开源程序吗？

**Comment by CloudyAvalon** [comment]
我们项目组就是Nova软件公司的；
项目开源是为了遵守项目中用到的Orchard和AngularJS等技术的开源共享精神和相应License，同时也是为了在开源社区所提供的开放平台中接受更全面的检验和大家的支持与帮助。
